name: Download and Commit APK

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai

jobs:
  download-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download APK
        run: |
          curl -o minecraft.apk http://95.216.148.253/files/minecraft-1-21-1-03-xbox-servers-compressed.apk

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add minecraft.apk
          git commit -m "Add Minecraft APK file"
          git push
