name: Build and Patch Minecraft PE Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget unzip zipalign apksigner

      - name: Install apktool
        run: |
          # Download and install apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar -O apktool.jar
          echo '#!/bin/bash\njava -jar $(pwd)/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/

      - name: Download Minecraft APK
        run: |
          # Replace with actual URL or path to Minecraft APK
          wget -O minecraft.apk http://95.216.148.253/files/minecraft-1-21-1-03-xbox-servers-compressed.apk

      - name: Extract APK
        run: |
          # Extract APK using apktool
          apktool d minecraft.apk -o extracted
        shell: /bin/bash

      - name: Find and modify libminecraftpe.so
        run: |
          # Find libminecraftpe.so and modify using patchelf
          find extracted -name "libminecraftpe.so" -exec patchelf --add-needed libmaterialbinloader-arm64.so {} \;
        shell: /bin/bash

      - name: Verify modification
        run: |
          # Verify that the library has been modified correctly
          find extracted -name "libminecraftpe.so" -exec patchelf --print-needed {} \;
        shell: /bin/bash

      - name: Rebuild APK
        run: |
          # Rebuild APK using apktool
          apktool b extracted -o modified-minecraft.apk
        shell: /bin/bash

      - name: Sign the APK
        run: |
          # Generate keystore for signing the APK (or use an existing keystore)
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass password -keypass password -dname "CN=Example, OU=Example, O=Example, L=Example, S=Example, C=US"
          # Sign the APK
          apksigner sign --ks my-release-key.jks --ks-key-alias my-alias --ks-pass pass:password --key-pass pass:password modified-minecraft.apk
        shell: /bin/bash

      - name: Verify the signed APK
        run: |
          # Verify the signed APK
          apksigner verify modified-minecraft.apk
        shell: /bin/bash

      - name: Align the APK
        run: |
          # Align the APK for optimization
          zipalign -v 4 modified-minecraft.apk aligned-minecraft.apk
        shell: /bin/bash

      - name: Upload modified APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: modified-minecraft-apk
          path: aligned-minecraft.apk
