name: Build and Patch Minecraft PE Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip zipalign apksigner openjdk-8-jre

      - name: Set up Java 8 environment
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Install apktool
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar -O apktool.jar
          echo '#!/bin/bash\njava -jar $(pwd)/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/
        shell: bash

      - name: Download Minecraft APK
        run: |
          wget -O minecraft.apk http://95.216.148.253/files/minecraft-1-21-1-03-xbox-servers-compressed.apk

      - name: Extract APK
        run: |
          apktool d minecraft.apk -o extracted
        shell: bash

      - name: Find and modify libminecraftpe.so
        run: |
          find extracted -name "libminecraftpe.so" -exec patchelf --add-needed libmaterialbinloader-arm64.so {} \;
        shell: bash

      - name: Verify modification
        run: |
          find extracted -name "libminecraftpe.so" -exec patchelf --print-needed {} \;
        shell: bash

      - name: Rebuild APK
        run: |
          apktool b extracted -o modified-minecraft.apk
        shell: bash

      - name: Sign the APK
        run: |
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass password -keypass password -dname "CN=Example, OU=Example, O=Example, L=Example, S=Example, C=US"
          apksigner sign --ks my-release-key.jks --ks-key-alias my-alias --ks-pass pass:password --key-pass pass:password modified-minecraft.apk
        shell: bash

      - name: Verify the signed APK
        run: |
          apksigner verify modified-minecraft.apk
        shell: bash

      - name: Align the APK
        run: |
          zipalign -v 4 modified-minecraft.apk aligned-minecraft.apk
        shell: bash

      - name: Upload modified APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: modified-minecraft-apk
          path: aligned-minecraft.apk